### ISSUE TITLE
node_modules heavy/failing

### ISSUE THREAD

**Issue by JerrySievert** [terraformer-js/terraformer#15]
looks like there's a few extremely heavy prerequisites:

```
~/w/s/terraformer-1   master  npm install

> fsevents@1.2.4 install /Users/jerry/work/sandbox/terraformer-1/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jerry/work/sandbox/terraformer-1/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> electron@1.8.8 postinstall /Users/jerry/work/sandbox/terraformer-1/node_modules/electron
> node install.js

Downloading electron-v1.8.8-darwin-x64.zip
Error: read ECONNRESET
/Users/jerry/work/sandbox/terraformer-1/node_modules/electron/install.js:47
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.8.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jerry/.npm/_logs/2019-01-21T21_18_42_614Z-debug.log
```

failing at electron install - if we're installing electron for something this simple, we're doing something really wrong.

**Comment by jgravois** [comment]
Electron is installed to run browser tests (via browserify).

what would you recommend as an alternative?
running the test suite in Node.js only?
relying on Chrome/Firefox to already be installed?

**Comment by JerrySievert** [comment]
## What's Expected

tests are for the development and maintenance of the projects, to help ensure correctness and for regressions: they're not for end-user deployments.

that leaves tests under a select few circumstances:

* integration tests
* bug fixes
* feature development


### Integration Tests

full integration tests should be both robust and automated.  here is where we should be building a matrix of environments including multiple versions of node and automated browser testing across multiple browsers and versions. 

important to have integration tests, under some very specific circumstances:

* pull requests
* commits
* releases

this is extremely heavyweight and comprehensive.  note that we do not have that now.

### Bug Fixes

bug fixes tend to be made by either core developers or extremely passionate users.  most users, when encountering a bug, are usually able to figure out a way to reproduce it, report it, and leave bug fixes to the core development team.

bugs tend to fall under one of the following categories:

* incorrect behavior - not meeting a spec or some requirement
* incompatibility - not working as expected in some environment

both of these scenarios would require additional tests and/or additional environments added to the integration matrix.

### Feature Development

feature development occurs typically by the core team, and occasionally by very dedicated community members.  feature development should allow for specifications, rapid development, and quick, easy to run tests.  remember, new features cannot and will not be accepted until they pass a list of criteria:

* documented
* reviewed
* runs in multiple environments

## What We Have

* tests tied to specific node versions (7.2.2)
* tests tied to specific chromium versions (via electron)
* extremely heavyweight for bug fixers (~1/3gb install footprint)
* little documentation for development

### Integration Tests

we have a very minimal, single-version travis configuration that, while heavyweight, is not a matrix and tied to very specific versions of node and chromium, as installed via the babel packages.  it is not flexible, and really no more than a checkbox at this point.

### Bug Fixes

we discourage casual bug fixers by requiring 1/3gb of installs with very little documentation of process, other than requiring to read the source and make guesses.

### Feature Development

yes, we should expect that someone doing feature development has a browser installed.

**Comment by JerrySievert** [comment]
sounds good - we can solve a lot just by documentation btw :)

**Comment by jgravois** [comment]
see https://github.com/terraformer-js/terraformer/pull/16
