### ISSUE TITLE
port @terraformer/wkt

### ISSUE THREAD

**Issue by jgravois** [terraformer-js/terraformer#3]

**Comment by jgravois** [comment]
ok @JerrySievert, i'm done porting the arcgis parser and spatial predicates. if you have any trouble getting acclimated in the monorepo, please holler.

**Comment by JerrySievert** [comment]
I'm slowly on it :)

**Comment by jgravois** [comment]
no rush. the bone stock JSDoc actually ain't bad.

* [`@terraformer/spatial`](https://terraformer-js.github.io/terraformer/module-@terraformer_arcgis.html)
* [`@terraformer/arcgis`](https://terraformer-js.github.io/terraformer/module-@terraformer_spatial.html)

**Comment by jgravois** [comment]
i was bored last night so i decided to just knock this out.

#17 still uses `jison`, but it points at a [fork](https://github.com/zaach/jison/pull/326) that introduces a _tiny_ feature to help us ship both a ES Module _and_ a UMD.

**Comment by JerrySievert** [comment]
Awesome. I kept meaning to get reengaged but things kept taking priority. And that’s the same jison fork I had planned on using. I’ll try to take a look either tonight at the airport if time or when I make it home.

**Comment by jgravois** [comment]
> I kept meaning to get reengaged but things kept taking priority.

no rush, but a sanity check would be _most_ appreciated Señor @JerrySievert.

i really enjoyed your [`JSON v JSONB`](https://legitimatesounding.com/blog/json_v_jsonb.html) blog post a couple weeks back!

**Comment by JerrySievert** [comment]
Sanity check is the least of what I can do :)

And thanks! That came out of a perplexing email chain I received via plv8. If you’re interested in what came out of it, go take a look at the recent changes on plv8/plv8 3.0alpha branch (sorry, no link on phone).  Ended up switching to a direct jsonb to v8::object conversion and changed some memory contexts around.
