### ISSUE TITLE
typescript typings

### ISSUE THREAD

**Issue by gavinr** [terraformer-js/terraformer#46]
When I try to use

```
import { arcgisToGeoJSON } from "@terraformer/arcgis";
```

in a TypeScript project, I get the error:

```
semantic error TS7016: Could not find a declaration file for module '@terraformer/arcgis'.
```

How can we make these available? I think there was a [previous version](https://www.npmjs.com/package/@types/arcgis-to-geojson-utils), perhaps we can use those?

**Comment by jgravois** [comment]
we definitely should be able to reuse those.

@zakjan already tackled @terraformer/spatial (see https://github.com/terraformer-js/terraformer/pull/34)

**Comment by murrple-1** [comment]
There appears to not yet be typings for `@terraformer/wkt`.... I would argue this issue is not yet closable

**Comment by HansBrende** [comment]
@gavinr `@terraformer/wkt` still has no typings available...
