### ISSUE TITLE
Add support for Z values

### ISSUE THREAD

**Issue by juliancox** [terraformer-js/terraformer#61]
At the moment Z values in a geojson point get stripped.  it looks as though the issue us in the geojsonToArcGIS funciton in terraformer/packages/arcgis/src/geojson.js.  Line 61 has:  
result.y = geojson.coordinates[1];
There is no:
if (geojson.coordinates[2]) result.z = geojson.coordinates[2]
I'm not sure if there are other areas that also need updating.
Thanks!

**Comment by jgravois** [comment]
a PR for this would be welcome

**Comment by jgravois** [comment]
released in [`v2.1.0`](https://www.npmjs.com/package/@terraformer/arcgis/v/2.1.0) thanks to @barrynickel 🚀🎉
