### ISSUE TITLE
wkt not support GEOMETRYCOLLECTION

### ISSUE THREAD

**Issue by yudonghai200** [terraformer-js/terraformer#82]
Uncaught Error: Unable to parse: Error: Parse error on line 1:
GEOMETRYCOLLECTION(P
^
Expecting 'POINT', 'LINESTRING', 'POLYGON', 'MULTIPOINT', 'MULTILINESTRING', 'MULTIPOLYGON', got 'INVALID'

**Comment by yudonghai200** [comment]
use wktToGeoJSON function params is `GEOMETRYCOLLECTION(POINT(4 6),LINESTRING(4 6,7 10))`

**Comment by jgravois** [comment]
a PR that introduces support for this would be welcome.

**Comment by yudonghai200** [comment]
thx

**Comment by jgravois** [comment]
closing, but a PR at any point in the future would be welcome.
