### ISSUE TITLE
this.parseError is not a function

### ISSUE THREAD

**Issue by hbarrameda** [terraformer-js/terraformer#92]
The function wktToGeoJSON of package **@terraformer/wkt** version 2.1.2 fails with error:
 _Unable to parse: TypeError: this.parseError is not a function_
when the wkt is invalid. 

To reproduce it just do 
_wkt.wktToGeoJSON("POINT(0,0)")_

**Comment by jgravois** [comment]
a PR to catch the error and return a more informative message would be welcome.

**Comment by mpalmerlee** [comment]
Thank you for maintaining this useful library @jgravois, I just started using it for a GIS project and hit this error also, the linked PR seems to address it 🙌
